Ext.define('Chaching.model.base.TransactionDetailsModel', {
    extend: 'Chaching.model.base.BaseModel',
    config: {
        searchEntityName: ''
    },
    fields: [
        { name: 'accountingItemId', type: 'int', isPrimaryKey: true },
        { name: 'accountingDocumentId', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'itemLinkId', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'itemLink', type: 'string' },
        { name: 'ledgerReference', type: 'string' },
        { name: 'ledgerDate', type: 'date' },
        { name: 'ledgerYyyymm', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'accountId', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'accountNumber', type: 'string' },
        { name: 'jobId', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'jobNumber', type: 'string' },
        { name: 'itemMemo', type: 'string' },
        { name: 'isAsset', type: 'boolean' },
        { name: 'accountRef1', type: 'string' },
        { name: 'accountRef2', type: 'string' },
        { name: 'accountRef3', type: 'string' },
        { name: 'accountRef4', type: 'string' },
        { name: 'accountRef5', type: 'string' },
        { name: 'accountRef6', type: 'string' },
        { name: 'accountRef7', type: 'string' },
        { name: 'accountRef8', type: 'string' },
        { name: 'accountRef9', type: 'string' },
        { name: 'accountRef10', type: 'string' },
        { name: 'subAccountId1', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'subAccountId2', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'subAccountId3', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'subAccountId4', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'subAccountId5', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'subAccountId6', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'subAccountId7', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'subAccountId8', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'subAccountId9', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'subAccountId10', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'subAccountNumber1', type: 'string' },
        { name: 'subAccountNumber2', type: 'string' },
        { name: 'subAccountNumber3', type: 'string' },
        { name: 'subAccountNumber4', type: 'string' },
        { name: 'subAccountNumber5', type: 'string' },
        { name: 'subAccountNumber6', type: 'string' },
        { name: 'subAccountNumber7', type: 'string' },
        { name: 'subAccountNumber8', type: 'string' },
        { name: 'subAccountNumber9', type: 'string' },
        { name: 'subAccountNumber10', type: 'string' },
        { name: 'typeOf1099T4Id', type: 'int', defaultVaule: null, convert: nullHandler },
        { name: 'typeOf1099T4', type: 'string' },
        { name: 'amount', type: 'float', defaultValue: 0.00 },
        { name: 'companyCurrencyAmount', type: 'float', defaultValue: null, convert: nullHandler },
        { name: 'currencyAdjustmentAmount', type: 'float', defaultValue: null, convert: nullHandler },
        { name: 'originalItemId', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'originalItem', type: 'string' },
        { name: 'accountingItemIdLink', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'originalItemaccountingItemLink', type: 'string' },
        { name: 'isChanged', type: 'boolean' },
        { name: 'isActive', type: 'boolean' },
        { name: 'typeOfInactiveStatusId', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'typeOfInactiveStatus', type: 'string' },
        { name: 'reconciliationId', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'reconciliation', type: 'string' },
        { name: 'accountingItemOrigAmount', type: 'float', defaultValue: null, convert: nullHandler },
        { name: 'accountingItemTypeOfModificationId', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'accountingItemTypeOfModification', type: 'string' },
        { name: 'accountingItemOrigId', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'accountingItemOrig', type: 'string' },
        { name: 'ictJobId', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'ictJob', type: 'string' },
        { name: 'ictAccountingItemId', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'ictAccountingItem', type: 'string' },
        { name: 'taxRebateId', type: 'int', defaultValue: null, convert: nullHandler },
        { name: 'taxRebateNumber', type: 'string' },
        { name: 'currencyOverrideRate', type: 'float', defaultValue: null, convert: nullHandler },
        { name: 'functionalCurrencyAmount', type: 'float', defaultValue: null, convert: nullHandler },
        { name: 'typeOfCurrencyRateId', type: 'int', defaultVaule: null, convert: nullHandler },
        { name: 'typeOfCurrencyRate', type: 'string' },
        { name: 'typeOfCurrencyId', type: 'int', defaultVaule: null, convert: nullHandler },
        { name: 'typeOfCurrency', type: 'string' },
        { name: 'homeCurAmount', type: 'float', defaultValue: null, convert: nullHandler },
        { name: 'customForexRate', type: 'float', defaultValue: null, convert: nullHandler },
        { name: 'isSplit', type: 'boolean' },
        { name: 'SplitGroupCls', type: 'string' }//Temporary field for row coloring
    ]
});
