Ext.define('Chaching.model.financials.AccountingItemModel', {
    extend: 'Chaching.model.base.BaseModel',
    config: {
        searchEntityName: ''
    },
    fields: [
{ name: 'accountingItemId', type: 'int', isPrimaryKey: true },
{ name: 'accountingDocumentId ', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'typeOfTransactionId', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'typeOfAmountId', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'itemLinkId', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'ledgerReference', type: 'string' },
{ name: 'ledgerDate', type: 'date' },
{ name: 'ledgerYyyymm', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'accountId', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'jobId', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'itemMemo', type: 'string' },
{ name: 'isAsset', type: 'boolean' },
{ name: 'accountRef1', type: 'string' },
{ name: 'accountRef2', type: 'string' },
{ name: 'accountRef3', type: 'string' },
{ name: 'accountRef4', type: 'string' },
{ name: 'accountRef5', type: 'string' },
{ name: 'accountRef6', type: 'string' },
{ name: 'accountRef7', type: 'string' },
{ name: 'accountRef8', type: 'string' },
{ name: 'accountRef9', type: 'string' },
{ name: 'accountRef10', type: 'string' },
{ name: 'subAccountId1', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'subAccountId2', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'subAccountId3', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'subAccountId4', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'subAccountId5', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'subAccountId6', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'subAccountId7', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'subAccountId8', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'subAccountId9', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'subAccountId10', type: 'int', defaultValue: null, convert: nullHandler }, 
{ name: 'typeOf1099T4Id', type: 'int', defaultVaule: null, convert: nullHandler },
{ name: 'amount', type: 'float', defaultValue: null, convert: nullHandler },
{ name: 'companyCurrencyAmount', type: 'float', defaultValue: null, convert: nullHandler },
{ name: 'currencyAdjustmentAmount', type: 'float', defaultValue: null, convert: nullHandler },
{ name: 'OriginalItemId', type: 'int', defaultValue: null, convert: nullHandler },
{ name: ' AccountingItemIdLink', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'isChanged', type: 'boolean' },
{ name: 'isActive', type: 'boolean' },
{ name: 'typeOfInactiveStatusId ', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'teconciliationId', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'accountingItemOrigAmount', type: 'float', defaultValue: null, convert: nullHandler },
{ name: 'accountingItemTypeOfModificationId', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'AccountingItemOrigId', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'ictJobId', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'ictAccountingItemId', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'taxRebateId', type: 'int', defaultValue: null, convert: nullHandler },
{ name: 'currencyOverrideRate', type: 'float', defaultValue: null, convert: nullHandler },
{ name: 'functionalCurrencyAmount', type: 'float', defaultValue: null, convert: nullHandler },
{ name: 'typeOfCurrencyRateId', type: 'int', defaultVaule: null, convert: nullHandler },
{ name: 'typeOfCurrencyId', type: 'int', defaultVaule: null, convert: nullHandler },
{ name: 'homeCurAmount', type: 'float', defaultValue: null, convert: nullHandler },
{ name: 'customForexRate', type: 'float', defaultValue: null, convert: nullHandler }
    ]
});