using System.Linq;
using CAPS.CORPACCOUNTING.EntityFramework;
using CAPS.CORPACCOUNTING.Masters;
using System.Collections.Generic;

namespace CAPS.CORPACCOUNTING.Migrations.Seed
{
    public class DefaultValueAddedTaxRecoveryCreator
    {
        public static List<ValueAddedTaxRecoveryUnit> InitialValueAddedTaxRecoveryList { get; private set; }

        private readonly CORPACCOUNTINGDbContext _context;

        static DefaultValueAddedTaxRecoveryCreator()
        {
            InitialValueAddedTaxRecoveryList = new List<ValueAddedTaxRecoveryUnit>
            {
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 1,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 2,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 3,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 4,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 5,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 6,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 7,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 8,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 9,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 10,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 11,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 13,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 14,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 15,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 16,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 17,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 18,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 19,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 20,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 21,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 23,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 24,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 25,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 26,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 27,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 29,
                    typeofvatrecoveryid: TypeOfVatRecovery.Miscellaneous, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 1, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 2, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 3, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 4, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 5, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 6, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 7, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 8, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 9, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 10, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 11, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 13, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 14, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 15, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 16, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 17, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 18, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 19, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 20, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 21, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 23, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 24, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 25, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 26, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 27, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 29, typeofvatrecoveryid: TypeOfVatRecovery.CarRental,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 1, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 2, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 3, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 4, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 5, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 6, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 7, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 8, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 9, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 10, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 11, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 13, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 14, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 15, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 16, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 17, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 18, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 19, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 20, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 21, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 23, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 24, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 25, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 26, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 27, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 29, typeofvatrecoveryid: TypeOfVatRecovery.Meals,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 1, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 2, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 3, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 4, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 5, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 6, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 7, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 8, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 9, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 10, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 11, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 13, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 14, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 15, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 16, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 17, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 18, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 19, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 20, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 21, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 23, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 24, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 25, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 26, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 27, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 29, typeofvatrecoveryid: TypeOfVatRecovery.Fuel,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 1, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 2, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 3, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 4, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 5, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 6, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 7, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 8, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 9, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 10, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 11, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 13, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 14, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 15, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 16, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 17, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 18, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 19, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 20, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 21, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 23, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 24, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 25, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 26, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 27, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 29, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),


                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 1, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 2, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 3, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 4, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 5, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 6, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 7, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 8, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 9, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 10, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 11, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 13, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 14, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 15, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 16, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 17, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 18, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 19, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 20, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 21, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 23, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 24, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 25, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 26, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 27, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 29, typeofvatrecoveryid: TypeOfVatRecovery.Telephone,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 1,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 2,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 3,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 4,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 5,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 6,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 7,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 8,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 9,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 10,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 11,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 13,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 14,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 15,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 16,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 17,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 18,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 19,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 20,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 21,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 23,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 24,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 25,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 26,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 27,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 29,
                    typeofvatrecoveryid: TypeOfVatRecovery.OtherBusinessExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 1,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 2,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 3,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 4,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 5,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 6,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 7,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 8,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 9,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 10,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 11,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 13,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 14,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 15,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 16,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 17,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 18,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 19,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 20,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 21,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 23,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 24,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 25,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 26,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 27,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 29,
                    typeofvatrecoveryid: TypeOfVatRecovery.BusinessOperatingExpense, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 1,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 2,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 3,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 4,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 5,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 6,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 7,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 8,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 9,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 10,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 11,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 13,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 14,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 15,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 16,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 17,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 18,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 19,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 20,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 21,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 23,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 24,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 25,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 26,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 27,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 29,
                    typeofvatrecoveryid: TypeOfVatRecovery.ProfessionalServices, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 1, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 2, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 3, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 4, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 5, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 6, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 7, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 8, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 9, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 10, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 11, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 13, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 14, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 15, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 16, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 17, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 18, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 19, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 20, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 21, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 23, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 24, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 25, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 26, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 27, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 29, typeofvatrecoveryid: TypeOfVatRecovery.TradeFair,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 1,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 2,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 3,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 4,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 5,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 6,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 7,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 8,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 9,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 10,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 11,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 13,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 14,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 15,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 16,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 17,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 18,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 19,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 20,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 21,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 23,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 24,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 25,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 26,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 27,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 29,
                    typeofvatrecoveryid: TypeOfVatRecovery.GoodsOrMachinesOrEquipment, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 1, typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 2, typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 3, typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 4, typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 5, typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 6, typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 7, typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 8, typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 9, typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods,
                    isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 10,
                    typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 11,
                    typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 13,
                    typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 14,
                    typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 15,
                    typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 16,
                    typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 17,
                    typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 18,
                    typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 19,
                    typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 20,
                    typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 21,
                    typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 23,
                    typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 24,
                    typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 25,
                    typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 26,
                    typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 27,
                    typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 29,
                    typeofvatrecoveryid: TypeOfVatRecovery.ExportGoods, isactive: true),
                new ValueAddedTaxRecoveryUnit(valueaddedtaxtypeid: 30,
                    typeofvatrecoveryid: TypeOfVatRecovery.GeneralSalesTax, isactive: true)
            };
        }


        public DefaultValueAddedTaxRecoveryCreator(CORPACCOUNTINGDbContext context)
        {
            _context = context;
        }

        public void Create()
        {
            ValueAddedTaxRecoveryList();
        }

        private void ValueAddedTaxRecoveryList()
        {
            foreach (var valueAddedTaxRecovery in InitialValueAddedTaxRecoveryList)
            {
                AddValueAddedTaxRecoveryListIfNotExists(valueAddedTaxRecovery);
            }
        }
        private void AddValueAddedTaxRecoveryListIfNotExists(ValueAddedTaxRecoveryUnit valueAddedTaxRecovery)
        {
            if (_context.ValueAddedTaxRecoveryUnit.Any(l => l.ValueAddedTaxTypeId == valueAddedTaxRecovery.ValueAddedTaxTypeId &&
            l.TypeOfVatRecoveryId == valueAddedTaxRecovery.TypeOfVatRecoveryId))
            {
                return;
            }

            _context.ValueAddedTaxRecoveryUnit.Add(valueAddedTaxRecovery);

            _context.SaveChanges();
        }

    }
}



