
Ext.define('Chaching.view.profile.loginAttempts.LoginAttemptList', {
    extend: 'Ext.view.View',

    requires: [
        'Chaching.view.profile.loginAttempts.LoginAttemptListController'
    ],

    controller: 'profile-loginattempts-loginattemptlist',
    store: 'profile.loginAttempts.LoginAttemptStore',
    scrollable:true,
    tpl: [
        '<tpl for=".">',
        '<div class="col-xs-12">',
        '<div class="alert bg-grey-cararra bg-font-grey-cararra">',
        '<div class="row">',
        '<div class="col-xs-3 text-center">',
        '<img src="' + abp.appPath + 'Profile/GetProfilePicture?t=65214896300' + '" class="img-circle" width="50" height="50"><br/>',
        '<span class="label label-success"> {result} </span>',
        '</div>',
        '<div class="col-xs-9">',
        '<div class="row">',
        '<label class="control-label col-sm-3 text-right">' + app.localize("IpAddress") + '</label>',
        '<div class="col-sm-9">',
        '<p class="form-control-static">',
        '{clientIpAddress}',
        '</p>',
        '</div>',
        '</div>',
        '<div class="row">',
        '<label class="control-label col-sm-3 text-right">'+app.localize("Client")+'</label>',
        '<div class="col-sm-9">',
        '<p class="form-control-static">',
        '{clientName}',
        '</p>',
        '</div>',
        '</div>',
        '<div class="row">',
        '<label class="control-label col-sm-3 text-right">'+app.localize("Browser")+'</label>',
        '<div class="col-sm-9">',
        '<p class="form-control-static">',
        '{browserInfo}',
        '</p>',
        '</div>',
        '</div>',
        '<div class="row">',
        '<label class="control-label col-sm-3 text-right">'+app.localize("Time")+'</label>',
        '<div class="col-sm-9">',
        '<p class="form-control-static">',
        '{attemptedOn}',
        '</p>',
        '</div>',
        '</div>',
        '</div>',
        '</div>',
        '</div>',
        '</div>',
        '</tpl>'
    ],
    itemSelector: 'div.col-xs-12',
    height: '100%',
    width: '100%'
});
