namespace CAPS.CORPACCOUNTING.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Rename_Tables : DbMigration
    {
        public override void Up()
        {
            RenameTable(name: "dbo.CAPS_Accounts", newName: "CAPS_Account");
            RenameTable(name: "dbo.CAPS_COA", newName: "CAPS_ChartOfAccount");
            RenameTable(name: "dbo.CAPS_JobDetail", newName: "CAPS_JobCommercial");
            RenameTable(name: "dbo.CAPS_Customers", newName: "CAPS_Customer");
            RenameTable(name: "dbo.CAPS_CustomerPaymentTerms", newName: "CAPS_CustomerPaymentTerm");
            RenameTable(name: "dbo.CAPS_RollupCenter", newName: "CAPS_CostCenter");
            RenameTable(name: "dbo.CAPS_Vendors", newName: "CAPS_Vendor");
            RenameTable(name: "dbo.CAPS_VendorPaymentTerms", newName: "CAPS_VendorPaymentTerm");
            RenameTable(name: "dbo.CAPS_ARBillingTypes", newName: "CAPS_ARBillingType");
            RenameTable(name: "dbo.CAPS_JobPettyCashLog", newName: "CAPS_JobWrapPettyCashLog");
            RenameTable(name: "dbo.CAPS_JobPurchaseOrderLog", newName: "CAPS_JobWrapPurchaseOrderLog");
            RenameTable(name: "dbo.CAPS_JobLinks", newName: "CAPS_JobLink");
            DropForeignKey("dbo.CAPS_APHeaderTransactions", "AHTID", "dbo.CAPS_AccountingHeaderTransactions");
            DropForeignKey("dbo.CAPS_CashEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions");
            DropForeignKey("dbo.CAPS_PaymentEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions");
            DropForeignKey("dbo.CAPS_PayrollEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions");
            DropForeignKey("dbo.CAPS_PurchaseOrderEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions");
            DropForeignKey("dbo.CAPS_ARInvoiceEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions");
            DropForeignKey("dbo.CAPS_ChargeEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions");
            DropForeignKey("dbo.CAPS_JournalEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions");
            DropForeignKey("dbo.CAPS_PettyCashEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions");
            DropIndex("dbo.CAPS_APHeaderTransactions", new[] { "AHTID" });
            DropIndex("dbo.CAPS_CashEntryDocument", new[] { "AHTID" });
            DropIndex("dbo.CAPS_PaymentEntryDocument", new[] { "AHTID" });
            DropIndex("dbo.CAPS_PayrollEntryDocument", new[] { "AHTID" });
            DropIndex("dbo.CAPS_PurchaseOrderEntryDocument", new[] { "AHTID" });
            DropIndex("dbo.CAPS_ARInvoiceEntryDocument", new[] { "AHTID" });
            DropIndex("dbo.CAPS_ChargeEntryDocument", new[] { "AHTID" });
            DropIndex("dbo.CAPS_JournalEntryDocument", new[] { "AHTID" });
            DropIndex("dbo.CAPS_PettyCashEntryDocument", new[] { "AHTID" });
            RenameColumn(table: "dbo.CAPS_ChartOfAccount", name: "COAId", newName: "ChartOfAccountId");
            RenameColumn(table: "dbo.CAPS_JobCommercial", name: "JobDetailId", newName: "JobCommercialId");
            RenameColumn(table: "dbo.CAPS_CustomerPaymentTerm", name: "CustomerPayTermsId", newName: "ARPaymentTermId");
            RenameColumn(table: "dbo.CAPS_CostCenter", name: "RollupCenterId", newName: "CostCenterId");
            DropPrimaryKey("dbo.CAPS_AccountingHeaderTransactions");
            DropPrimaryKey("dbo.CAPS_ARInvoiceEntryDocument");
            DropPrimaryKey("dbo.CAPS_CashEntryDocument");
            DropPrimaryKey("dbo.CAPS_ChargeEntryDocument");
            DropPrimaryKey("dbo.CAPS_JournalEntryDocument");
            DropPrimaryKey("dbo.CAPS_APHeaderTransactions");
            DropPrimaryKey("dbo.CAPS_PaymentEntryDocument");
            DropPrimaryKey("dbo.CAPS_PayrollEntryDocument");
            DropPrimaryKey("dbo.CAPS_PettyCashEntryDocument");
            DropPrimaryKey("dbo.CAPS_PurchaseOrderEntryDocument");
            AlterColumn("dbo.CAPS_AccountingHeaderTransactions", "AHTID", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.CAPS_ARInvoiceEntryDocument", "AHTID", c => c.Long(nullable: false));
            AlterColumn("dbo.CAPS_CashEntryDocument", "AHTID", c => c.Long(nullable: false));
            AlterColumn("dbo.CAPS_ChargeEntryDocument", "AHTID", c => c.Long(nullable: false));
            AlterColumn("dbo.CAPS_JournalEntryDocument", "AHTID", c => c.Long(nullable: false));
            AlterColumn("dbo.CAPS_APHeaderTransactions", "AHTID", c => c.Long(nullable: false));
            AlterColumn("dbo.CAPS_PaymentEntryDocument", "AHTID", c => c.Long(nullable: false));
            AlterColumn("dbo.CAPS_PayrollEntryDocument", "AHTID", c => c.Long(nullable: false));
            AlterColumn("dbo.CAPS_PettyCashEntryDocument", "AHTID", c => c.Long(nullable: false));
            AlterColumn("dbo.CAPS_PurchaseOrderEntryDocument", "AHTID", c => c.Long(nullable: false));
            AddPrimaryKey("dbo.CAPS_AccountingHeaderTransactions", "AHTID");
            AddPrimaryKey("dbo.CAPS_ARInvoiceEntryDocument", "AHTID");
            AddPrimaryKey("dbo.CAPS_CashEntryDocument", "AHTID");
            AddPrimaryKey("dbo.CAPS_ChargeEntryDocument", "AHTID");
            AddPrimaryKey("dbo.CAPS_JournalEntryDocument", "AHTID");
            AddPrimaryKey("dbo.CAPS_APHeaderTransactions", "AHTID");
            AddPrimaryKey("dbo.CAPS_PaymentEntryDocument", "AHTID");
            AddPrimaryKey("dbo.CAPS_PayrollEntryDocument", "AHTID");
            AddPrimaryKey("dbo.CAPS_PettyCashEntryDocument", "AHTID");
            AddPrimaryKey("dbo.CAPS_PurchaseOrderEntryDocument", "AHTID");
            CreateIndex("dbo.CAPS_APHeaderTransactions", "AHTID");
            CreateIndex("dbo.CAPS_CashEntryDocument", "AHTID");
            CreateIndex("dbo.CAPS_PaymentEntryDocument", "AHTID");
            CreateIndex("dbo.CAPS_PayrollEntryDocument", "AHTID");
            CreateIndex("dbo.CAPS_PurchaseOrderEntryDocument", "AHTID");
            CreateIndex("dbo.CAPS_ARInvoiceEntryDocument", "AHTID");
            CreateIndex("dbo.CAPS_ChargeEntryDocument", "AHTID");
            CreateIndex("dbo.CAPS_JournalEntryDocument", "AHTID");
            CreateIndex("dbo.CAPS_PettyCashEntryDocument", "AHTID");
            AddForeignKey("dbo.CAPS_APHeaderTransactions", "AHTID", "dbo.CAPS_AccountingHeaderTransactions", "AHTID");
            AddForeignKey("dbo.CAPS_CashEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions", "AHTID");
            AddForeignKey("dbo.CAPS_PaymentEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions", "AHTID");
            AddForeignKey("dbo.CAPS_PayrollEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions", "AHTID");
            AddForeignKey("dbo.CAPS_PurchaseOrderEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions", "AHTID");
            AddForeignKey("dbo.CAPS_ARInvoiceEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions", "AHTID");
            AddForeignKey("dbo.CAPS_ChargeEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions", "AHTID");
            AddForeignKey("dbo.CAPS_JournalEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions", "AHTID");
            AddForeignKey("dbo.CAPS_PettyCashEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions", "AHTID");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.CAPS_PettyCashEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions");
            DropForeignKey("dbo.CAPS_JournalEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions");
            DropForeignKey("dbo.CAPS_ChargeEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions");
            DropForeignKey("dbo.CAPS_ARInvoiceEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions");
            DropForeignKey("dbo.CAPS_PurchaseOrderEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions");
            DropForeignKey("dbo.CAPS_PayrollEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions");
            DropForeignKey("dbo.CAPS_PaymentEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions");
            DropForeignKey("dbo.CAPS_CashEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions");
            DropForeignKey("dbo.CAPS_APHeaderTransactions", "AHTID", "dbo.CAPS_AccountingHeaderTransactions");
            DropIndex("dbo.CAPS_PettyCashEntryDocument", new[] { "AHTID" });
            DropIndex("dbo.CAPS_JournalEntryDocument", new[] { "AHTID" });
            DropIndex("dbo.CAPS_ChargeEntryDocument", new[] { "AHTID" });
            DropIndex("dbo.CAPS_ARInvoiceEntryDocument", new[] { "AHTID" });
            DropIndex("dbo.CAPS_PurchaseOrderEntryDocument", new[] { "AHTID" });
            DropIndex("dbo.CAPS_PayrollEntryDocument", new[] { "AHTID" });
            DropIndex("dbo.CAPS_PaymentEntryDocument", new[] { "AHTID" });
            DropIndex("dbo.CAPS_CashEntryDocument", new[] { "AHTID" });
            DropIndex("dbo.CAPS_APHeaderTransactions", new[] { "AHTID" });
            DropPrimaryKey("dbo.CAPS_PurchaseOrderEntryDocument");
            DropPrimaryKey("dbo.CAPS_PettyCashEntryDocument");
            DropPrimaryKey("dbo.CAPS_PayrollEntryDocument");
            DropPrimaryKey("dbo.CAPS_PaymentEntryDocument");
            DropPrimaryKey("dbo.CAPS_APHeaderTransactions");
            DropPrimaryKey("dbo.CAPS_JournalEntryDocument");
            DropPrimaryKey("dbo.CAPS_ChargeEntryDocument");
            DropPrimaryKey("dbo.CAPS_CashEntryDocument");
            DropPrimaryKey("dbo.CAPS_ARInvoiceEntryDocument");
            DropPrimaryKey("dbo.CAPS_AccountingHeaderTransactions");
            AlterColumn("dbo.CAPS_PurchaseOrderEntryDocument", "AHTID", c => c.Int(nullable: false));
            AlterColumn("dbo.CAPS_PettyCashEntryDocument", "AHTID", c => c.Int(nullable: false));
            AlterColumn("dbo.CAPS_PayrollEntryDocument", "AHTID", c => c.Int(nullable: false));
            AlterColumn("dbo.CAPS_PaymentEntryDocument", "AHTID", c => c.Int(nullable: false));
            AlterColumn("dbo.CAPS_APHeaderTransactions", "AHTID", c => c.Int(nullable: false));
            AlterColumn("dbo.CAPS_JournalEntryDocument", "AHTID", c => c.Int(nullable: false));
            AlterColumn("dbo.CAPS_ChargeEntryDocument", "AHTID", c => c.Int(nullable: false));
            AlterColumn("dbo.CAPS_CashEntryDocument", "AHTID", c => c.Int(nullable: false));
            AlterColumn("dbo.CAPS_ARInvoiceEntryDocument", "AHTID", c => c.Int(nullable: false));
            AlterColumn("dbo.CAPS_AccountingHeaderTransactions", "AHTID", c => c.Int(nullable: false, identity: true));
            AddPrimaryKey("dbo.CAPS_PurchaseOrderEntryDocument", "AHTID");
            AddPrimaryKey("dbo.CAPS_PettyCashEntryDocument", "AHTID");
            AddPrimaryKey("dbo.CAPS_PayrollEntryDocument", "AHTID");
            AddPrimaryKey("dbo.CAPS_PaymentEntryDocument", "AHTID");
            AddPrimaryKey("dbo.CAPS_APHeaderTransactions", "AHTID");
            AddPrimaryKey("dbo.CAPS_JournalEntryDocument", "AHTID");
            AddPrimaryKey("dbo.CAPS_ChargeEntryDocument", "AHTID");
            AddPrimaryKey("dbo.CAPS_CashEntryDocument", "AHTID");
            AddPrimaryKey("dbo.CAPS_ARInvoiceEntryDocument", "AHTID");
            AddPrimaryKey("dbo.CAPS_AccountingHeaderTransactions", "AHTID");
            RenameColumn(table: "dbo.CAPS_CostCenter", name: "CostCenterId", newName: "RollupCenterId");
            RenameColumn(table: "dbo.CAPS_CustomerPaymentTerm", name: "ARPaymentTermId", newName: "CustomerPayTermsId");
            RenameColumn(table: "dbo.CAPS_JobCommercial", name: "JobCommercialId", newName: "JobDetailId");
            RenameColumn(table: "dbo.CAPS_ChartOfAccount", name: "ChartOfAccountId", newName: "COAId");
            CreateIndex("dbo.CAPS_PettyCashEntryDocument", "AHTID");
            CreateIndex("dbo.CAPS_JournalEntryDocument", "AHTID");
            CreateIndex("dbo.CAPS_ChargeEntryDocument", "AHTID");
            CreateIndex("dbo.CAPS_ARInvoiceEntryDocument", "AHTID");
            CreateIndex("dbo.CAPS_PurchaseOrderEntryDocument", "AHTID");
            CreateIndex("dbo.CAPS_PayrollEntryDocument", "AHTID");
            CreateIndex("dbo.CAPS_PaymentEntryDocument", "AHTID");
            CreateIndex("dbo.CAPS_CashEntryDocument", "AHTID");
            CreateIndex("dbo.CAPS_APHeaderTransactions", "AHTID");
            AddForeignKey("dbo.CAPS_PettyCashEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions", "AHTID");
            AddForeignKey("dbo.CAPS_JournalEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions", "AHTID");
            AddForeignKey("dbo.CAPS_ChargeEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions", "AHTID");
            AddForeignKey("dbo.CAPS_ARInvoiceEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions", "AHTID");
            AddForeignKey("dbo.CAPS_PurchaseOrderEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions", "AHTID");
            AddForeignKey("dbo.CAPS_PayrollEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions", "AHTID");
            AddForeignKey("dbo.CAPS_PaymentEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions", "AHTID");
            AddForeignKey("dbo.CAPS_CashEntryDocument", "AHTID", "dbo.CAPS_AccountingHeaderTransactions", "AHTID");
            AddForeignKey("dbo.CAPS_APHeaderTransactions", "AHTID", "dbo.CAPS_AccountingHeaderTransactions", "AHTID");
            RenameTable(name: "dbo.CAPS_JobLink", newName: "CAPS_JobLinks");
            RenameTable(name: "dbo.CAPS_JobWrapPurchaseOrderLog", newName: "CAPS_JobPurchaseOrderLog");
            RenameTable(name: "dbo.CAPS_JobWrapPettyCashLog", newName: "CAPS_JobPettyCashLog");
            RenameTable(name: "dbo.CAPS_ARBillingType", newName: "CAPS_ARBillingTypes");
            RenameTable(name: "dbo.CAPS_VendorPaymentTerm", newName: "CAPS_VendorPaymentTerms");
            RenameTable(name: "dbo.CAPS_Vendor", newName: "CAPS_Vendors");
            RenameTable(name: "dbo.CAPS_CostCenter", newName: "CAPS_RollupCenter");
            RenameTable(name: "dbo.CAPS_CustomerPaymentTerm", newName: "CAPS_CustomerPaymentTerms");
            RenameTable(name: "dbo.CAPS_Customer", newName: "CAPS_Customers");
            RenameTable(name: "dbo.CAPS_JobCommercial", newName: "CAPS_JobDetail");
            RenameTable(name: "dbo.CAPS_ChartOfAccount", newName: "CAPS_COA");
            RenameTable(name: "dbo.CAPS_Account", newName: "CAPS_Accounts");
        }
    }
}
