// <auto-generated />
namespace CAPS.CORPACCOUNTING.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Remove_IMustHaveOrganizationColumn_FromTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Remove_IMustHaveOrganizationColumn_FromTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201607070841528_Remove_IMustHaveOrganizationColumn_FromTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
