// <auto-generated />
namespace CAPS.CORPACCOUNTING.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_to_Abp0112and0113 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_to_Abp0112and0113));
        
        string IMigrationMetadata.Id
        {
            get { return "201609071829496_Update_to_Abp0.11.2and0.11.3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
