namespace CAPS.CORPACCOUNTING.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Add_LajitId_Tables : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.CAPS_AccountingControl", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_Entity", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_AccountingDocument", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_Batch", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_BankAccount", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_Account", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_ChartOfAccount", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_Job", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_JobCommercial", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_Customer", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_CustomerPaymentTerm", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_SalesRep", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_Employee", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_CostCenter", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_Vendor", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_VendorPaymentTerm", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_PettyCashAccount", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_BankRecControl", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_UploadDocumentLog", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_PaymentRequestHistory", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_AccountingItem", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_SubAccount", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_ AccountingLayoutItem", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_TypeOfAccountingLayout", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_TypeOfHeading", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_AccountingLayout", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_AccountRollup", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_ChartOfAccountRollup", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_AccountTotal", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_FiscalPeriod", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_FiscalYear", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_Address", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_Approval", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_ApprovedSOX", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_ARBillingType", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_ARInvoiceBuild", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_ARInvoiceSchedule", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_ARStatementDetail", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_ARStatementInfo", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_ARYTDInvoice", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_AttachedObject", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_BankAccountPaymentRange", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_BankAccountUser", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_BankRecAdjustment", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_BankRecCleared", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_BankStatementDetails", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_BatchExecutionResult", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_BatchReport", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_BatchReportItem", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_Code1099T4Rate", "LajitId", c => c.Short());
            AddColumn("dbo.CAPS_Code1099T4Type", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_ConsolidationDetail", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_ConsolidationGroup", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_TypeOfAccount", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_TypeOfAccountClassification", "LajitId", c => c.Short());
            AddColumn("dbo.CAPS_ControlAccount", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_CurrencyRate", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_CurrencyTypeOfRate", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_CurrencyType", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_CustomerGroup", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_EmailAddress", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_EmailMsgAddress", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_EmailMsgLog", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_Email", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_ErrorMessage", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_FedExTranslation", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_GroupItemRange", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_GroupItem", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_GroupTotal", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_ICTRelation", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_InvoicePayment", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_JobAccount", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_JobBudgetDetails", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_JobBudget", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_JobEFC", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_ProjectControlPeriod", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_JobWrapPettyCashLog", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_JobWrapPurchaseOrderLog", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_JobType", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_TypeOfFormatMask", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_JobWrapAmexLog", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_JobWrapCheckLog", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_JobWrapDocumentLog", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_JobWrapEntryDocument", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_JobWrapPayrollLog", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_JobWrapSalesLog", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_JobLink", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_NewCOATrim", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_NotedObject", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_PaymentPrintHistory", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_PayrollControlFringe", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_PayrollControl", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_PCGrid", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_Phone", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_ProfitRule", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_TypeOfProfitCalc", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_ProfitVariable", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_ReceiptHistory", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_Region", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_ReportDistributionList", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_ReportDistribution", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_Report", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_SalesRegion", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_SecureObject", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_SICCode", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_TaxRebate", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_TypeOfFinReport", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_TypeOfGenericProcess", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_UploadAddress", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_UploadName", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_UserReport", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_ValueAddedTaxRecovery", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_ValueAddedTaxType", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_VendorGroup", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_VendorShipMethod", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_WebAddress", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_WorkFlowLog", "LajitId", c => c.Int());
            AddColumn("dbo.CAPS_WorkFlow", "LajitId", c => c.Long());
            AddColumn("dbo.CAPS_WorkSheet1099", "LajitId", c => c.Long());
        }
        
        public override void Down()
        {
            DropColumn("dbo.CAPS_WorkSheet1099", "LajitId");
            DropColumn("dbo.CAPS_WorkFlow", "LajitId");
            DropColumn("dbo.CAPS_WorkFlowLog", "LajitId");
            DropColumn("dbo.CAPS_WebAddress", "LajitId");
            DropColumn("dbo.CAPS_VendorShipMethod", "LajitId");
            DropColumn("dbo.CAPS_VendorGroup", "LajitId");
            DropColumn("dbo.CAPS_ValueAddedTaxType", "LajitId");
            DropColumn("dbo.CAPS_ValueAddedTaxRecovery", "LajitId");
            DropColumn("dbo.CAPS_UserReport", "LajitId");
            DropColumn("dbo.CAPS_UploadName", "LajitId");
            DropColumn("dbo.CAPS_UploadAddress", "LajitId");
            DropColumn("dbo.CAPS_TypeOfGenericProcess", "LajitId");
            DropColumn("dbo.CAPS_TypeOfFinReport", "LajitId");
            DropColumn("dbo.CAPS_TaxRebate", "LajitId");
            DropColumn("dbo.CAPS_SICCode", "LajitId");
            DropColumn("dbo.CAPS_SecureObject", "LajitId");
            DropColumn("dbo.CAPS_SalesRegion", "LajitId");
            DropColumn("dbo.CAPS_Report", "LajitId");
            DropColumn("dbo.CAPS_ReportDistribution", "LajitId");
            DropColumn("dbo.CAPS_ReportDistributionList", "LajitId");
            DropColumn("dbo.CAPS_Region", "LajitId");
            DropColumn("dbo.CAPS_ReceiptHistory", "LajitId");
            DropColumn("dbo.CAPS_ProfitVariable", "LajitId");
            DropColumn("dbo.CAPS_TypeOfProfitCalc", "LajitId");
            DropColumn("dbo.CAPS_ProfitRule", "LajitId");
            DropColumn("dbo.CAPS_Phone", "LajitId");
            DropColumn("dbo.CAPS_PCGrid", "LajitId");
            DropColumn("dbo.CAPS_PayrollControl", "LajitId");
            DropColumn("dbo.CAPS_PayrollControlFringe", "LajitId");
            DropColumn("dbo.CAPS_PaymentPrintHistory", "LajitId");
            DropColumn("dbo.CAPS_NotedObject", "LajitId");
            DropColumn("dbo.CAPS_NewCOATrim", "LajitId");
            DropColumn("dbo.CAPS_JobLink", "LajitId");
            DropColumn("dbo.CAPS_JobWrapSalesLog", "LajitId");
            DropColumn("dbo.CAPS_JobWrapPayrollLog", "LajitId");
            DropColumn("dbo.CAPS_JobWrapEntryDocument", "LajitId");
            DropColumn("dbo.CAPS_JobWrapDocumentLog", "LajitId");
            DropColumn("dbo.CAPS_JobWrapCheckLog", "LajitId");
            DropColumn("dbo.CAPS_JobWrapAmexLog", "LajitId");
            DropColumn("dbo.CAPS_TypeOfFormatMask", "LajitId");
            DropColumn("dbo.CAPS_JobType", "LajitId");
            DropColumn("dbo.CAPS_JobWrapPurchaseOrderLog", "LajitId");
            DropColumn("dbo.CAPS_JobWrapPettyCashLog", "LajitId");
            DropColumn("dbo.CAPS_ProjectControlPeriod", "LajitId");
            DropColumn("dbo.CAPS_JobEFC", "LajitId");
            DropColumn("dbo.CAPS_JobBudget", "LajitId");
            DropColumn("dbo.CAPS_JobBudgetDetails", "LajitId");
            DropColumn("dbo.CAPS_JobAccount", "LajitId");
            DropColumn("dbo.CAPS_InvoicePayment", "LajitId");
            DropColumn("dbo.CAPS_ICTRelation", "LajitId");
            DropColumn("dbo.CAPS_GroupTotal", "LajitId");
            DropColumn("dbo.CAPS_GroupItem", "LajitId");
            DropColumn("dbo.CAPS_GroupItemRange", "LajitId");
            DropColumn("dbo.CAPS_FedExTranslation", "LajitId");
            DropColumn("dbo.CAPS_ErrorMessage", "LajitId");
            DropColumn("dbo.CAPS_Email", "LajitId");
            DropColumn("dbo.CAPS_EmailMsgLog", "LajitId");
            DropColumn("dbo.CAPS_EmailMsgAddress", "LajitId");
            DropColumn("dbo.CAPS_EmailAddress", "LajitId");
            DropColumn("dbo.CAPS_CustomerGroup", "LajitId");
            DropColumn("dbo.CAPS_CurrencyType", "LajitId");
            DropColumn("dbo.CAPS_CurrencyTypeOfRate", "LajitId");
            DropColumn("dbo.CAPS_CurrencyRate", "LajitId");
            DropColumn("dbo.CAPS_ControlAccount", "LajitId");
            DropColumn("dbo.CAPS_TypeOfAccountClassification", "LajitId");
            DropColumn("dbo.CAPS_TypeOfAccount", "LajitId");
            DropColumn("dbo.CAPS_ConsolidationGroup", "LajitId");
            DropColumn("dbo.CAPS_ConsolidationDetail", "LajitId");
            DropColumn("dbo.CAPS_Code1099T4Type", "LajitId");
            DropColumn("dbo.CAPS_Code1099T4Rate", "LajitId");
            DropColumn("dbo.CAPS_BatchReportItem", "LajitId");
            DropColumn("dbo.CAPS_BatchReport", "LajitId");
            DropColumn("dbo.CAPS_BatchExecutionResult", "LajitId");
            DropColumn("dbo.CAPS_BankStatementDetails", "LajitId");
            DropColumn("dbo.CAPS_BankRecCleared", "LajitId");
            DropColumn("dbo.CAPS_BankRecAdjustment", "LajitId");
            DropColumn("dbo.CAPS_BankAccountUser", "LajitId");
            DropColumn("dbo.CAPS_BankAccountPaymentRange", "LajitId");
            DropColumn("dbo.CAPS_AttachedObject", "LajitId");
            DropColumn("dbo.CAPS_ARYTDInvoice", "LajitId");
            DropColumn("dbo.CAPS_ARStatementInfo", "LajitId");
            DropColumn("dbo.CAPS_ARStatementDetail", "LajitId");
            DropColumn("dbo.CAPS_ARInvoiceSchedule", "LajitId");
            DropColumn("dbo.CAPS_ARInvoiceBuild", "LajitId");
            DropColumn("dbo.CAPS_ARBillingType", "LajitId");
            DropColumn("dbo.CAPS_ApprovedSOX", "LajitId");
            DropColumn("dbo.CAPS_Approval", "LajitId");
            DropColumn("dbo.CAPS_Address", "LajitId");
            DropColumn("dbo.CAPS_FiscalYear", "LajitId");
            DropColumn("dbo.CAPS_FiscalPeriod", "LajitId");
            DropColumn("dbo.CAPS_AccountTotal", "LajitId");
            DropColumn("dbo.CAPS_ChartOfAccountRollup", "LajitId");
            DropColumn("dbo.CAPS_AccountRollup", "LajitId");
            DropColumn("dbo.CAPS_AccountingLayout", "LajitId");
            DropColumn("dbo.CAPS_TypeOfHeading", "LajitId");
            DropColumn("dbo.CAPS_TypeOfAccountingLayout", "LajitId");
            DropColumn("dbo.CAPS_ AccountingLayoutItem", "LajitId");
            DropColumn("dbo.CAPS_SubAccount", "LajitId");
            DropColumn("dbo.CAPS_AccountingItem", "LajitId");
            DropColumn("dbo.CAPS_PaymentRequestHistory", "LajitId");
            DropColumn("dbo.CAPS_UploadDocumentLog", "LajitId");
            DropColumn("dbo.CAPS_BankRecControl", "LajitId");
            DropColumn("dbo.CAPS_PettyCashAccount", "LajitId");
            DropColumn("dbo.CAPS_VendorPaymentTerm", "LajitId");
            DropColumn("dbo.CAPS_Vendor", "LajitId");
            DropColumn("dbo.CAPS_CostCenter", "LajitId");
            DropColumn("dbo.CAPS_Employee", "LajitId");
            DropColumn("dbo.CAPS_SalesRep", "LajitId");
            DropColumn("dbo.CAPS_CustomerPaymentTerm", "LajitId");
            DropColumn("dbo.CAPS_Customer", "LajitId");
            DropColumn("dbo.CAPS_JobCommercial", "LajitId");
            DropColumn("dbo.CAPS_Job", "LajitId");
            DropColumn("dbo.CAPS_ChartOfAccount", "LajitId");
            DropColumn("dbo.CAPS_Account", "LajitId");
            DropColumn("dbo.CAPS_BankAccount", "LajitId");
            DropColumn("dbo.CAPS_Batch", "LajitId");
            DropColumn("dbo.CAPS_AccountingDocument", "LajitId");
            DropColumn("dbo.CAPS_Entity", "LajitId");
            DropColumn("dbo.CAPS_AccountingControl", "LajitId");
        }
    }
}
