// <auto-generated />
namespace CAPS.CORPACCOUNTING.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Abp_ModuleZero_10_Upgrade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Abp_ModuleZero_10_Upgrade));
        
        string IMigrationMetadata.Id
        {
            get { return "201605121536510_Abp_ModuleZero_10_Upgrade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
