// <auto-generated />
namespace CAPS.CORPACCOUNTING.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_TypeOfChart_Enum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_TypeOfChart_Enum));
        
        string IMigrationMetadata.Id
        {
            get { return "201609061618211_Add_TypeOfChart_Enum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
