var timeZonecultureList = [
    { "TimeZoneOffSetId": "-12:00", "CultureFormat": "en-US", "Description": "International Date Line West" },
    { "TimeZoneOffSetId": "-11:00", "CultureFormat": "en-US", "Description": "Midway Island, Samoa" },
    { "TimeZoneOffSetId": "-10:00", "CultureFormat": "en-US", "Description": "Hawaii" },
    { "TimeZoneOffSetId": "-09:00", "CultureFormat": "en-US", "Description": "Alaska" },
    { "TimeZoneOffSetId": "-08:00", "CultureFormat": "en-US", "Description": "Pacific Time (US & Canada)" },
    { "TimeZoneOffSetId": "-07:00", "CultureFormat": "en-US", "Description": "Arizona" },
    { "TimeZoneOffSetId": "-06:00", "CultureFormat": "en-US", "Description": "Central America, Saskatchewan" },
    { "TimeZoneOffSetId": "-05:00", "CultureFormat": "en-US", "Description": "Indiana, Bogota, Lima, Quito, Rio Branco" },
    { "TimeZoneOffSetId": "-04:00", "CultureFormat": "en-CA", "Description": "Atlantic time (Canada), Manaus, Santiago" },
    { "TimeZoneOffSetId": "-03:30", "CultureFormat": "en-CA", "Description": "Newfoundland" },
    { "TimeZoneOffSetId": "-03:00", "CultureFormat": "kl-GL", "Description": "Greenland, Brasilia, Montevideo" },
    { "TimeZoneOffSetId": "-02:00", "CultureFormat": "en-US", "Description": "Mid-Atlantic" },
    { "TimeZoneOffSetId": "-01:00", "CultureFormat": "en-US", "Description": "Azores" },
    { "TimeZoneOffSetId": "0", "CultureFormat": "fr-FR", "Description": "Casablanca, Monrovia, Reykjavik" },
    { "TimeZoneOffSetId": "+01:00", "CultureFormat": "nl-BE", "Description": "Amsterdam, Berlin, Rome, Vienna, Prague, Brussels" },
    { "TimeZoneOffSetId": "+02:00", "CultureFormat": "el-GR", "Description": "Amman, Athens, Istanbul, Beirut, Cairo, Jerusalem" },
    { "TimeZoneOffSetId": "+03:00", "CultureFormat": "ru-RU", "Description": "Baghdad, Moscow, St. Petersburg, Volgograd" },
    { "TimeZoneOffSetId": "+03:30", "CultureFormat": "fa-IR", "Description": "Tehran" },
    { "TimeZoneOffSetId": "+04:00", "CultureFormat": "ar-OM", "Description": "Abu Dhadi, Muscat" },
    { "TimeZoneOffSetId": "+04:30", "CultureFormat": "ps-AF", "Description": "Kabul" },
    { "TimeZoneOffSetId": "+05:00", "CultureFormat": "ur-PK", "Description": "Ekaterinburg" },
    { "TimeZoneOffSetId": "+05:30", "CultureFormat": "hi-IN", "Description": "Chennai, Kolkata, Mumbai, New Delhi, Sri Jayawardenepura" },
    { "TimeZoneOffSetId": "+05:45", "CultureFormat": "ne-NP", "Description": "Kathmandu" },
    { "TimeZoneOffSetId": "+06:00", "CultureFormat": "bn-BD", "Description": "Astana, Dhaka" },
    { "TimeZoneOffSetId": "+06:30", "CultureFormat": "en-US", "Description": "Yangon (Rangoon)" },
    { "TimeZoneOffSetId": "+07:00", "CultureFormat": "th-TH", "Description": "Krasnoyarsk" },
    { "TimeZoneOffSetId": "+08:00", "CultureFormat": "zh-HK", "Description": "Beijing, Hong Kong, Singapore, Taipei" },
    { "TimeZoneOffSetId": "+09:00", "CultureFormat": "ko-KR", "Description": "Yakutsk" },
    { "TimeZoneOffSetId": "+09:30", "CultureFormat": "en-AU", "Description": "Darwin" },
    { "TimeZoneOffSetId": "+10:00", "CultureFormat": "en-AU", "Description": "Brisbane, Guam, Port Moresby" },
    { "TimeZoneOffSetId": "+11:00", "CultureFormat": "ru-RU", "Description": "Magadan, Solomon Is., New Caledonia" },
    { "TimeZoneOffSetId": "+12:00", "CultureFormat": "en-NZ", "Description": "Auckland, Wellington" },
    { "TimeZoneOffSetId": "+13:00", "CultureFormat": "en-NZ", "Description": "Nuku'alofa" }
];

